# fly.toml app configuration file generated for fuelfit-1 on 2025-09-30T22:47:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fuelfit-1'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'pb_data'
  destination = '/pb/pb_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
